services:
  - type: web
    name: banking-db-service
    env: docker
    plan: free # Or select an appropriate plan
    dockerfilePath: Dockerfile
    region: ohio # Choose appropriate region
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://spicelife576:skiPPer8711@cluster0.pmbmm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DATABASE
        value: bankdb
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
